name = "opensheet"
main = "index.js"
account_id = "f2a0306525ffd1fe138c4c3fbb79a126"
compatibility_date = "2022-11-20"

# Uncomment if you don’t have a custom domain.
# workers_dev = true

# For custom domain — comment out if you don’t have a custom domain.
route = "opensheet.elk.sh/*"
